{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# PINYASURI FLIGHT METRICS ANALYSIS\n",
    "\n",
    "This notebook computes flight performance metrics from raw telemetry data collected during drone missions."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## IMPORT LIBRARIES"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "from math import radians, sin, cos, sqrt, asin\n",
    "from pathlib import Path\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "# File paths\n",
    "RAW_CSV = Path(\"raw_flight_data.csv\")  # Updated filename to match actual data\n",
    "SUMMARY_CSV = Path(\"flight_metrics_summary.csv\")\n",
    "OVERALL_CSV = Path(\"overall_metrics.csv\")\n",
    "\n",
    "EARTH_RADIUS_M = 6371000  # meters"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## HAVERSINE DISTANCE FUNCTION"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def haversine(lat1, lon1, lat2, lon2):\n",
    "    \"\"\"Calculate great circle distance between two GPS coordinates\"\"\"\n",
    "    lat1, lon1, lat2, lon2 = map(radians, [lat1, lon1, lat2, lon2])\n",
    "    dlat = lat2 - lat1\n",
    "    dlon = lon2 - lon1\n",
    "    a = sin(dlat/2)**2 + cos(lat1) * cos(lat2) * sin(dlon/2)**2\n",
    "    return 2 * EARTH_RADIUS_M * asin(sqrt(a))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## LOAD DATA"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Load CSV with error handling\n",
    "try:\n",
    "    df = pd.read_csv(\n",
    "        RAW_CSV,\n",
    "        engine=\"python\",\n",
    "        on_bad_lines=\"skip\"\n",
    "    )\n",
    "    \n",
    "    # Convert timestamp to datetime\n",
    "    df[\"timestamp_utc\"] = pd.to_datetime(df[\"timestamp_utc\"])\n",
    "    \n",
    "    print(f\"✓ Loaded {len(df)} telemetry records\")\n",
    "    print(f\"✓ Columns: {list(df.columns)}\")\n",
    "    print(f\"\\nFirst few rows:\")\n",
    "    display(df.head())\n",
    "    \n",
    "except FileNotFoundError:\n",
    "    print(f\"❌ Error: {RAW_CSV} not found!\")\n",
    "    print(\"Please ensure the raw flight data CSV exists.\")\n",
    "except Exception as e:\n",
    "    print(f\"❌ Error loading data: {e}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## DATA OVERVIEW"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Check unique flights\n",
    "flights = df.groupby(\"flight_id\")\n",
    "print(f\"Total flights in dataset: {len(flights)}\")\n",
    "print(f\"\\nFlight IDs:\")\n",
    "for flight_id, group in flights:\n",
    "    print(f\"  - {flight_id}: {len(group)} records\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## METRIC QUALITY THRESHOLDS"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "THRESHOLDS = {\n",
    "    \"altitude_stability_index\": {\n",
    "        \"good\": 5.0,\n",
    "        \"acceptable\": 10.0\n",
    "    },\n",
    "    \"imu_vibration_rms_m_s2\": {\n",
    "        \"good\": 8.0,\n",
    "        \"acceptable\": 12.0\n",
    "    },\n",
    "    \"waypoint_accuracy_rms_m\": {\n",
    "        \"good\": 1.5,\n",
    "        \"acceptable\": 3.0\n",
    "    },\n",
    "    \"hover_position_jitter_rms_m\": {\n",
    "        \"good\": 1.0,\n",
    "        \"acceptable\": 2.5\n",
    "    },\n",
    "    \"avg_flight_duration_s\": {\n",
    "        \"good\": 60.0,\n",
    "        \"acceptable\": 30.0\n",
    "    }\n",
    "}\n",
    "\n",
    "def judge_metric(value, good_thresh, acceptable_thresh, higher_is_better=False):\n",
    "    \"\"\"Evaluate metric quality based on thresholds\"\"\"\n",
    "    if np.isnan(value):\n",
    "        return \"N/A\"\n",
    "    \n",
    "    if higher_is_better:\n",
    "        if value >= good_thresh:\n",
    "            return \"Good\"\n",
    "        elif value >= acceptable_thresh:\n",
    "            return \"Acceptable\"\n",
    "        else:\n",
    "            return \"Poor\"\n",
    "    else:\n",
    "        if value <= good_thresh:\n",
    "            return \"Good\"\n",
    "        elif value <= acceptable_thresh:\n",
    "            return \"Acceptable\"\n",
    "        else:\n",
    "            return \"Poor\""
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## PER-FLIGHT METRIC COMPUTATION"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "results = []\n",
    "\n",
    "for flight_id, f in flights:\n",
    "    print(f\"Processing {flight_id}...\")\n",
    "    \n",
    "    # 1. Altitude / Attitude Stability\n",
    "    roll_std = f[\"roll_deg\"].std()\n",
    "    pitch_std = f[\"pitch_deg\"].std()\n",
    "    yaw_std = f[\"yaw_deg\"].std()\n",
    "    alt_std = f[\"alt_m\"].std()\n",
    "    \n",
    "    # 2. IMU Acceleration RMS\n",
    "    accel_mag = np.sqrt(\n",
    "        f[\"accel_x_m_s2\"]**2 +\n",
    "        f[\"accel_y_m_s2\"]**2 +\n",
    "        f[\"accel_z_m_s2\"]**2\n",
    "    )\n",
    "    imu_rms = np.sqrt(np.mean(accel_mag**2))\n",
    "    \n",
    "    # 3. Waypoint Navigation Accuracy\n",
    "    wp_valid = f[f[\"waypoint_index\"] >= 0].copy()\n",
    "    \n",
    "    if not wp_valid.empty:\n",
    "        wp_valid[\"horizontal_error_m\"] = wp_valid.apply(\n",
    "            lambda r: haversine(\n",
    "                r[\"lat_deg\"], r[\"lon_deg\"],\n",
    "                r[\"waypoint_lat_deg\"], r[\"waypoint_lon_deg\"]\n",
    "            ) if pd.notna(r[\"waypoint_lat_deg\"]) and pd.notna(r[\"waypoint_lon_deg\"]) else np.nan,\n",
    "            axis=1\n",
    "        )\n",
    "        \n",
    "        waypoint_error_mean = wp_valid[\"horizontal_error_m\"].mean()\n",
    "        waypoint_error_rms = np.sqrt(np.mean(wp_valid[\"horizontal_error_m\"]**2))\n",
    "    else:\n",
    "        waypoint_error_mean = np.nan\n",
    "        waypoint_error_rms = np.nan\n",
    "    \n",
    "    # 4. Hover Position Jitter\n",
    "    hover = f[f[\"is_hovering\"] == True].copy()\n",
    "    \n",
    "    if not hover.empty and len(hover) > 1:\n",
    "        lat_mean = hover[\"lat_deg\"].mean()\n",
    "        lon_mean = hover[\"lon_deg\"].mean()\n",
    "        \n",
    "        hover[\"pos_error_m\"] = hover.apply(\n",
    "            lambda r: haversine(\n",
    "                r[\"lat_deg\"], r[\"lon_deg\"],\n",
    "                lat_mean, lon_mean\n",
    "            ),\n",
    "            axis=1\n",
    "        )\n",
    "        \n",
    "        hover_jitter_rms = np.sqrt(np.mean(hover[\"pos_error_m\"]**2))\n",
    "    else:\n",
    "        hover_jitter_rms = np.nan\n",
    "    \n",
    "    # 5. Flight Duration\n",
    "    flight_time_s = (\n",
    "        f[\"timestamp_utc\"].iloc[-1] -\n",
    "        f[\"timestamp_utc\"].iloc[0]\n",
    "    ).total_seconds()\n",
    "    \n",
    "    # Save results\n",
    "    results.append({\n",
    "        \"flight_id\": flight_id,\n",
    "        \"duration_s\": round(flight_time_s, 1),\n",
    "        \"roll_std_deg\": round(roll_std, 3),\n",
    "        \"pitch_std_deg\": round(pitch_std, 3),\n",
    "        \"yaw_std_deg\": round(yaw_std, 3),\n",
    "        \"altitude_std_m\": round(alt_std, 3),\n",
    "        \"imu_accel_rms_m_s2\": round(imu_rms, 3),\n",
    "        \"wp_error_mean_m\": round(waypoint_error_mean, 2),\n",
    "        \"wp_error_rms_m\": round(waypoint_error_rms, 2),\n",
    "        \"hover_jitter_rms_m\": round(hover_jitter_rms, 2)\n",
    "    })\n",
    "\n",
    "summary_df = pd.DataFrame(results)\n",
    "print(\"\\n✓ Per-flight metrics computed\")\n",
    "display(summary_df)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## SAVE SUMMARY"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "summary_df.to_csv(SUMMARY_CSV, index=False)\n",
    "print(f\"✓ Summary saved to {SUMMARY_CSV}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## OVERALL METRICS + QUALITY RATINGS"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "overall_metrics = {}\n",
    "\n",
    "# Altitude Stability Index\n",
    "alt_stability = np.nanmean([\n",
    "    summary_df[\"roll_std_deg\"].mean(),\n",
    "    summary_df[\"pitch_std_deg\"].mean(),\n",
    "    summary_df[\"yaw_std_deg\"].mean(),\n",
    "    summary_df[\"altitude_std_m\"].mean()\n",
    "])\n",
    "overall_metrics[\"altitude_stability_index\"] = round(alt_stability, 3)\n",
    "overall_metrics[\"altitude_stability_rating\"] = judge_metric(\n",
    "    alt_stability,\n",
    "    THRESHOLDS[\"altitude_stability_index\"][\"good\"],\n",
    "    THRESHOLDS[\"altitude_stability_index\"][\"acceptable\"]\n",
    ")\n",
    "\n",
    "# IMU Vibration\n",
    "imu_rms = summary_df[\"imu_accel_rms_m_s2\"].mean()\n",
    "overall_metrics[\"imu_vibration_rms_m_s2\"] = round(imu_rms, 3)\n",
    "overall_metrics[\"imu_vibration_rating\"] = judge_metric(\n",
    "    imu_rms,\n",
    "    THRESHOLDS[\"imu_vibration_rms_m_s2\"][\"good\"],\n",
    "    THRESHOLDS[\"imu_vibration_rms_m_s2\"][\"acceptable\"]\n",
    ")\n",
    "\n",
    "# Waypoint Accuracy\n",
    "wp_rms = summary_df[\"wp_error_rms_m\"].dropna().mean()\n",
    "overall_metrics[\"waypoint_accuracy_rms_m\"] = round(wp_rms, 2)\n",
    "overall_metrics[\"waypoint_accuracy_rating\"] = judge_metric(\n",
    "    wp_rms,\n",
    "    THRESHOLDS[\"waypoint_accuracy_rms_m\"][\"good\"],\n",
    "    THRESHOLDS[\"waypoint_accuracy_rms_m\"][\"acceptable\"]\n",
    ")\n",
    "\n",
    "# Hover Jitter\n",
    "hover_rms = summary_df[\"hover_jitter_rms_m\"].dropna().mean()\n",
    "overall_metrics[\"hover_position_jitter_rms_m\"] = round(hover_rms, 2)\n",
    "overall_metrics[\"hover_position_jitter_rating\"] = judge_metric(\n",
    "    hover_rms,\n",
    "    THRESHOLDS[\"hover_position_jitter_rms_m\"][\"good\"],\n",
    "    THRESHOLDS[\"hover_position_jitter_rms_m\"][\"acceptable\"]\n",
    ")\n",
    "\n",
    "# Flight Endurance\n",
    "avg_duration = summary_df[\"duration_s\"].mean()\n",
    "overall_metrics[\"avg_flight_duration_s\"] = round(avg_duration, 1)\n",
    "overall_metrics[\"flight_endurance_rating\"] = judge_metric(\n",
    "    avg_duration,\n",
    "    THRESHOLDS[\"avg_flight_duration_s\"][\"good\"],\n",
    "    THRESHOLDS[\"avg_flight_duration_s\"][\"acceptable\"],\n",
    "    higher_is_better=True\n",
    ")\n",
    "\n",
    "# Save and display\n",
    "overall_df = pd.DataFrame(overall_metrics, index=[\"overall\"])\n",
    "overall_df.to_csv(OVERALL_CSV)\n",
    "\n",
    "print(\"\\n✓ Overall metrics WITH quality ratings:\")\n",
    "display(overall_df.T)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## VISUALIZATIONS\n",
    "\n",
    "### 1. Altitude Stability"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Altitude over time\n",
    "plt.figure(figsize=(12, 4))\n",
    "plt.plot(df[\"timestamp_utc\"], df[\"alt_m\"])\n",
    "plt.xlabel(\"Time\")\n",
    "plt.ylabel(\"Altitude (m)\")\n",
    "plt.title(\"Altitude vs Time\")\n",
    "plt.grid(True)\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "\n",
    "# Stability components\n",
    "labels = [\"Roll\", \"Pitch\", \"Yaw\", \"Altitude\"]\n",
    "values = [\n",
    "    summary_df[\"roll_std_deg\"].mean(),\n",
    "    summary_df[\"pitch_std_deg\"].mean(),\n",
    "    summary_df[\"yaw_std_deg\"].mean(),\n",
    "    summary_df[\"altitude_std_m\"].mean()\n",
    "]\n",
    "\n",
    "plt.figure(figsize=(8, 5))\n",
    "plt.bar(labels, values, color=['#3498db', '#2ecc71', '#f39c12', '#e74c3c'])\n",
    "plt.ylabel(\"Standard Deviation\")\n",
    "plt.title(\"Altitude/Attitude Stability Components\")\n",
    "plt.grid(axis=\"y\", alpha=0.3)\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 2. IMU Acceleration"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Acceleration time series\n",
    "plt.figure(figsize=(12, 4))\n",
    "plt.plot(df[\"timestamp_utc\"], df[\"accel_x_m_s2\"], label=\"Accel X\", alpha=0.7)\n",
    "plt.plot(df[\"timestamp_utc\"], df[\"accel_y_m_s2\"], label=\"Accel Y\", alpha=0.7)\n",
    "plt.plot(df[\"timestamp_utc\"], df[\"accel_z_m_s2\"], label=\"Accel Z\", alpha=0.7)\n",
    "plt.xlabel(\"Time\")\n",
    "plt.ylabel(\"Acceleration (m/s²)\")\n",
    "plt.title(\"IMU Acceleration vs Time\")\n",
    "plt.legend()\n",
    "plt.grid(True, alpha=0.3)\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "\n",
    "# RMS per axis\n",
    "rms_x = np.sqrt(np.nanmean(df[\"accel_x_m_s2\"]**2))\n",
    "rms_y = np.sqrt(np.nanmean(df[\"accel_y_m_s2\"]**2))\n",
    "rms_z = np.sqrt(np.nanmean(df[\"accel_z_m_s2\"]**2))\n",
    "\n",
    "plt.figure(figsize=(8, 5))\n",
    "plt.bar([\"X\", \"Y\", \"Z\"], [rms_x, rms_y, rms_z], color=['#3498db', '#2ecc71', '#f39c12'])\n",
    "plt.ylabel(\"RMS Acceleration (m/s²)\")\n",
    "plt.title(\"IMU Acceleration RMS by Axis\")\n",
    "plt.grid(axis=\"y\", alpha=0.3)\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 3. Waypoint Navigation"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Flight path with waypoints\n",
    "wp_data = df[df[\"waypoint_index\"] >= 0]\n",
    "\n",
    "if not wp_data.empty:\n",
    "    plt.figure(figsize=(10, 8))\n",
    "    plt.plot(df[\"lon_deg\"], df[\"lat_deg\"], 'b-', label=\"Flight Path\", alpha=0.6)\n",
    "    plt.scatter(\n",
    "        wp_data[\"waypoint_lon_deg\"],\n",
    "        wp_data[\"waypoint_lat_deg\"],\n",
    "        marker=\"x\",\n",
    "        color='red',\n",
    "        s=100,\n",
    "        label=\"Waypoints\"\n",
    "    )\n",
    "    plt.xlabel(\"Longitude (deg)\")\n",
    "    plt.ylabel(\"Latitude (deg)\")\n",
    "    plt.title(\"Flight Path and Waypoints\")\n",
    "    plt.legend()\n",
    "    plt.grid(True, alpha=0.3)\n",
    "    plt.tight_layout()\n",
    "    plt.show()\n",
    "else:\n",
    "    print(\"No valid waypoint data available\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 4. Hover Stability"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "hover_df = df[df[\"is_hovering\"] == True]\n",
    "\n",
    "if not hover_df.empty:\n",
    "    # Position scatter\n",
    "    plt.figure(figsize=(8, 8))\n",
    "    plt.scatter(\n",
    "        hover_df[\"lon_deg\"],\n",
    "        hover_df[\"lat_deg\"],\n",
    "        s=10,\n",
    "        alpha=0.5\n",
    "    )\n",
    "    plt.xlabel(\"Longitude (deg)\")\n",
    "    plt.ylabel(\"Latitude (deg)\")\n",
    "    plt.title(\"Hover Position Scatter\")\n",
    "    plt.grid(True, alpha=0.3)\n",
    "    plt.axis('equal')\n",
    "    plt.tight_layout()\n",
    "    plt.show()\n",
    "    \n",
    "    # Jitter histogram\n",
    "    if len(hover_df) > 1:\n",
    "        mean_lat = hover_df[\"lat_deg\"].mean()\n",
    "        mean_lon = hover_df[\"lon_deg\"].mean()\n",
    "        \n",
    "        hover_df_copy = hover_df.copy()\n",
    "        hover_df_copy[\"jitter_m\"] = hover_df_copy.apply(\n",
    "            lambda r: haversine(\n",
    "                r[\"lat_deg\"], r[\"lon_deg\"],\n",
    "                mean_lat, mean_lon\n",
    "            ),\n",
    "            axis=1\n",
    "        )\n",
    "        \n",
    "        plt.figure(figsize=(10, 5))\n",
    "        plt.hist(hover_df_copy[\"jitter_m\"], bins=30, edgecolor='black', alpha=0.7)\n",
    "        plt.xlabel(\"Jitter Distance (m)\")\n",
    "        plt.ylabel(\"Frequency\")\n",
    "        plt.title(\"Hover Position Jitter Distribution\")\n",
    "        plt.grid(True, alpha=0.3)\n",
    "        plt.tight_layout()\n",
    "        plt.show()\n",
    "else:\n",
    "    print(\"No hover data available\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 5. Overall Metrics Summary"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Extract numeric metrics only\n",
    "metric_names = [k for k in overall_metrics.keys() if not k.endswith('_rating')]\n",
    "metric_values = [overall_metrics[k] for k in metric_names]\n",
    "\n",
    "plt.figure(figsize=(12, 6))\n",
    "bars = plt.bar(range(len(metric_names)), metric_values, \n",
    "               color=['#3498db', '#2ecc71', '#f39c12', '#e74c3c', '#9b59b6'])\n",
    "plt.xticks(range(len(metric_names)), metric_names, rotation=45, ha='right')\n",
    "plt.ylabel(\"Metric Value\")\n",
    "plt.title(\"Overall Flight Performance Metrics\")\n",
    "plt.grid(axis=\"y\", alpha=0.3)\n",
    "\n",
    "# Add ratings as labels\n",
    "for i, (name, value) in enumerate(zip(metric_names, metric_values)):\n",
    "    rating_key = f\"{name.replace('avg_', '').replace('_index', '')}_rating\"\n",
    "    if rating_key in overall_metrics:\n",
    "        rating = overall_metrics[rating_key]\n",
    "        color = {'Good': 'green', 'Acceptable': 'orange', 'Poor': 'red', 'N/A': 'gray'}.get(rating, 'black')\n",
    "        plt.text(i, value, f'\\n{rating}', ha='center', va='bottom', \n",
    "                color=color, fontweight='bold', fontsize=9)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "\n",
    "# Print summary table\n",
    "print(\"\\n\" + \"=\"*70)\n",
    "print(\"FLIGHT PERFORMANCE SUMMARY\")\n",
    "print(\"=\"*70)\n",
    "for key in overall_metrics:\n",
    "    if not key.endswith('_rating'):\n",
    "        rating_key = f\"{key.replace('avg_', '').replace('_index', '')}_rating\"\n",
    "        rating = overall_metrics.get(rating_key, 'N/A')\n",
    "        print(f\"{key:40s}: {overall_metrics[key]:10.3f}  [{rating}]\")\n",
    "print(\"=\"*70)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## FLIGHT DURATION ANALYSIS"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "if len(summary_df) > 1:\n",
    "    plt.figure(figsize=(10, 5))\n",
    "    plt.bar(range(len(summary_df)), summary_df[\"duration_s\"], \n",
    "           tick_label=summary_df[\"flight_id\"], color='#3498db', alpha=0.7)\n",
    "    plt.xlabel(\"Flight ID\")\n",
    "    plt.ylabel(\"Duration (seconds)\")\n",
    "    plt.title(\"Flight Duration Comparison\")\n",
    "    plt.xticks(rotation=45, ha='right')\n",
    "    plt.grid(axis=\"y\", alpha=0.3)\n",
    "    plt.tight_layout()\n",
    "    plt.show()\n",
    "else:\n",
    "    print(f\"